name: Update llama cpp nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }

permissions:
  pull-requests: write
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update llama cpp
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        name: Checkout latest
        with:
          submodules: recursive
      - name: create branch and save branch name
        run: |
          BRANCH_NAME=update-llama-cpp-$(date -I)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
      - name: update submodules
        run: git submodule update --remote
      - name: config git
        run: |
          git config --global user.email "marcus@utilityai.ca"
          git config --global user.name "Marcus Dunn"
      - name: commit
        run: git commit -am "updated llama.cpp"
      - name: push
        run: git push --set-upstream origin $BRANCH_NAME --force
      - name: close any outdated prs with the same name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --state open --json number,title | jq -r '.[] | select(.title | contains("'"$BRANCH_NAME"'")) | .number' | xargs -I {} gh pr close {}
      - name: create open pr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create --fill
      - name: Trigger the llama-cpp-rs-check workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{"event_type": "trigger-llama-cpp-rs-check", "client_payload": {"branch": "'"$BRANCH_NAME"'" }}'    

