name: Update llama cpp nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }

permissions:
  pull-requests: write
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update llama cpp
    steps:
      - name: Set date
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        name: Checkout latest
        with:
          submodules: recursive
      - name: Create branch
        run: git checkout -b update-llama-cpp-${{ env.DATE }}
      - name: Update submodules
        run: git submodule update --remote
      - name: Config git
        run: |
          git config --global user.email "marcus@utilityai.ca"
          git config --global user.name "Marcus Dunn"
      - name: Commit
        run: git commit -am "updated llama.cpp"
      - name: Push
        run: git push --set-upstream origin update-llama-cpp-${{ env.DATE }} --force
      - name: Close any outdated PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --json number,title --jq '.[] | select(.title | contains("Update llama-cpp")) | .number' | xargs -I {} gh pr close {}
      - name: Create open PR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create --fill --base update-llama-cpp-fix --head update-llama-cpp-${{ env.DATE }} --title "Update llama-cpp"
      - name: Trigger the llama-cpp-rs-check workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{"event_type": "trigger-llama-cpp-rs-check", "client_payload": { "ref": "update-llama-cpp-${{ env.DATE }}" }}'
